# Generated by Django 4.2.3 on 2023-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso3', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=100)),
                ('cpi_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('std_error', models.FloatField()),
                ('num_sources', models.IntegerField()),
                ('lower_ci', models.FloatField()),
                ('upper_ci', models.FloatField()),
                ('african_development_bank_cpia', models.FloatField()),
                ('bertelsmann_foundation_sustainable_governance_index', models.FloatField()),
                ('bertelsmann_foundation_transformation_index', models.FloatField()),
                ('economist_intelligence_unit_country_ratings', models.FloatField()),
                ('freedom_house_nations_in_transit', models.FloatField()),
                ('global_insights_country_risk_ratings', models.FloatField()),
                ('imd_world_competitiveness_yearbook', models.FloatField()),
                ('perc_asia_risk_guide', models.FloatField()),
                ('prs_international_country_risk_guide', models.FloatField()),
                ('varieties_of_democracy_project', models.FloatField()),
                ('world_bank_cpia', models.FloatField()),
                ('world_economic_forum_eos', models.FloatField()),
                ('world_justice_project_rule_of_law_index', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
