# Generated by Django 4.2.3 on 2023-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0002_cpi_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpi',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
