# Generated by Django 4.2.3 on 2023-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0003_alter_cpi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpi',
            name='num_sources',
        ),
        migrations.RemoveField(
            model_name='cpi',
            name='std_error',
        ),
        migrations.AddField(
            model_name='cpi',
            name='number_of_sources',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cpi',
            name='standard_error',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='african_development_bank_cpia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='bertelsmann_foundation_sustainable_governance_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='bertelsmann_foundation_transformation_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='cpi_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='economist_intelligence_unit_country_ratings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='freedom_house_nations_in_transit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='global_insights_country_risk_ratings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='imd_world_competitiveness_yearbook',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='lower_ci',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='perc_asia_risk_guide',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='prs_international_country_risk_guide',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='upper_ci',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='varieties_of_democracy_project',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='world_bank_cpia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='world_economic_forum_eos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cpi',
            name='world_justice_project_rule_of_law_index',
            field=models.FloatField(null=True),
        ),
    ]
