# Generated by Django 4.2.3 on 2023-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0005_remove_cpi_african_development_bank_cpia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('fsi_score', models.FloatField(null=True)),
            ],
        ),
    ]
