# Generated by Django 4.2.3 on 2023-07-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0006_fsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fsi',
            options={'verbose_name': 'Overview', 'verbose_name_plural': 'Overview'},
        ),
    ]
