# Generated by Django 4.2.3 on 2023-07-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0009_overview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fsi',
            options={},
        ),
    ]
