# Generated by Django 4.2.3 on 2023-07-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpiScraper', '0010_alter_fsi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fatf',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fsi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='name',
        ),
        migrations.AddField(
            model_name='cpi',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fatf',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fsi',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
